dataset_path: "csv"
dataset_kwargs:
  data_dir: /mnt/nushare2/data/mnulli/llava_ov/playground/mmbench/data_dev
  token: True
task: "mmbench_en_dev"
test_split: test
include: _default_template_mmbench_en_yaml
metric_list:
  - metric: gpt_eval_score
    aggregation: !function en_utils.mmbench_aggregate_dev_results_eval
    higher_is_better: true
  - metric: submission
    aggregation: !function en_utils.mmbench_aggregate_dev_results_submission
    higher_is_better: true