dataset_path: "csv"
dataset_kwargs:
  data_dir: /mnt/nushare2/data/mnulli/llava_ov/playground/mmvp/data/eval_data
task: "mmvp"
test_split: test
output_type: generate_until
doc_to_visual: !function utils.mmvp_doc_to_visual
doc_to_text: !function utils.mmvp_doc_to_text
doc_to_target: "answer"
# The return value of process_results will be used by metrics
process_results: !function utils.mmvp_process_results
# Note that the metric name can be either a registed metric function (such as the case for GQA) or a key name returned by process_results
metric_list:
  - metric: match_score
    aggregation: !function utils.mmvp_acc_results
    higher_is_better: true
lmms_eval_specific_kwargs:
  default:
    pre_prompt: ""
    post_prompt: "\nAnswer with the option's letter from the given choices directly. "
metadata:
  - version: 0.0
