dataset_path: csv
dataset_kwargs:
  data_dir: "/mnt/nushare2/data/mnulli/thesis/data/benchmarks/conme/data/replace_att"
task: "conme-replace-att" 
test_split: test
output_type: generate_until
doc_to_visual: !function utils.conme_doc_to_visual
doc_to_text: !function utils.conme_doc_to_text_mc
doc_to_target: "answer"
# Note that the metric name can be either a registed metric function (such as the case for GQA) or a key name returned by process_results
generation_kwargs:
  max_new_tokens: 100
  temperature: 0
  top_p: 0
  num_beams: 1
  do_sample: false
process_results: !function utils.conme_process_results
metric_list:
  - metric: string_matching_accuracy
    aggregation: !function utils.combine_accuracies
    higher_is_better: true
lmms_eval_specific_kwargs:
  default:
    pre_prompt: ""
    post_prompt: "\nAnswer with the option's letter from the given choices directly."
metadata:
  - version: 0.0