dataset_path: "parquet"
dataset_kwargs:
    data_dir: "/mnt/nushare2/data/stuzel/grader_info/v1"
task: "grader_info"
test_split: test
output_type: generate_until
doc_to_visual: !function utils.grader_info_to_visual
doc_to_text: !function utils.grader_info_to_text
doc_to_target: !function utils.grader_info_to_target
generation_kwargs:
  max_new_tokens: 300
  temperature: 0
  top_p: 0
  num_beams: 1
  do_sample: false
# The return value of process_results will be used by metrics
process_results: !function utils.grader_info_process_results
# Note that the metric name can be either a registed metric function (such as the case for GQA) or a key name returned by process_results
metric_list:
  - metric: is_graded_accuracy
    aggregation: !function utils.calculate_accuracy
    higher_is_better: true
  - metric: is_graded_precision
    aggregation: !function utils.calculate_precision
    higher_is_better: true
  - metric: is_graded_recall
    aggregation: !function utils.calculate_recall
    higher_is_better: true
  - metric: is_graded_f1
    aggregation: !function utils.calculate_f1
    higher_is_better: true
  - metric: certification_number_accuracy
    aggregation: !function utils.calculate_accuracy
    higher_is_better: true
  - metric: professional_grader_accuracy
    aggregation: !function utils.calculate_accuracy
    higher_is_better: true
  - metric: grade_accuracy
    aggregation: !function utils.calculate_accuracy
    higher_is_better: true
  - metric: regex_validity_rate
    aggregation: !function utils.regex_validity_rate
    higher_is_better: true
lmms_eval_specific_kwargs:
  default:
    pre_prompt: ''
    post_prompt: "Question: Please investigate the card and determine if it is graded. A graded card should have a slab; otherwise, it is NOT graded. Graders include PSA, BGS, CGC, SGC, and TGA. If the card is graded, please return the answer as raw values separated by `,` without spaces, in the format: <is_graded>,<certification_number>,<professional_grader>,<grade>. If the card is not graded, return the answer as: <is_graded>."
metadata:
  - version: 0.1
