dataset_path: "arrow"
dataset_kwargs:
  data_dir: "/mnt/nushare2/data/mnulli/llava_ov/playground/gowitheflow___aro-flickr-order/default/0.0.0/1f9485f69c87947812378a1aedf86410c86a0aa8"
task: "aro-flickr-order"
test_split: test
output_type: generate_until
doc_to_visual: !function utils.aro_order_doc_to_visual
doc_to_text: !function utils.aro_order_doc_to_text_mc
doc_to_target: "answer"
# Note that the metric name can be either a registed metric function (such as the case for GQA) or a key name returned by process_results
generation_kwargs:
  max_new_tokens: 100
  temperature: 0
  top_p: 0
  num_beams: 1
  do_sample: false
process_results: !function utils.aro_order_process_results
metric_list:
  - metric: string_matching_accuracy
    aggregation: !function utils.combine_accuracies
    higher_is_better: true
lmms_eval_specific_kwargs:
  default:
    pre_prompt: "Given one image and the candidate captions (A, B, C, D and E), which caption is the better description of the given image?"
    post_prompt: "Answer with the option's letter from the given choices directly, only give a single character answer - 'A', 'B', 'C', 'D' or 'E' and answer only with one letter without providing any reasoning."
metadata:
  - version: 0.0