dataset_path: "arrow"
dataset_kwargs:
  data_dir: "/mnt/nushare2/data/mnulli/llava_ov/playground/lmms-lab___hallusion_bench/default/0.0.0/cd417161857aefb23d878d42cf1bb53aa9dd646f/image_data"
task: "hallusion_bench_image"
test_split: test
output_type: generate_until
doc_to_visual: !function evaluate_hb.hb_doc_to_visual
doc_to_text: !function evaluate_hb.hb_doc_to_text
doc_to_target: "gt_answer_details"
process_results: !function evaluate_hb.hb_process_results
lmms_eval_specific_kwargs:
  default:
    pre_prompt: ""
    post_prompt: ""
generation_kwargs:
  max_new_tokens: 128
  temperature: 0
  top_p: 1.0
  num_beams: 1
  do_sample: false
metric_list:
  - metric: aAcc
    aggregation: !function evaluate_hb.hb_aggregation_result_aAcc
    higher_is_better: true
  - metric: qAcc
    aggregation: !function evaluate_hb.hb_aggregation_result_qAcc
    higher_is_better: true
  - metric: fAcc
    aggregation: !function evaluate_hb.hb_aggregation_result_fAcc
    higher_is_better: true
  # - metric: aAcc
  #  aggregation: !function evaluate_hb.hb_aggregation_result_aAcc_intern
  #  higher_is_better: true
  # - metric: qAcc
  #  aggregation: !function evaluate_hb.hb_aggregation_result_qAcc_intern
  #  higher_is_better: true
  # - metric: fAcc
  #  aggregation: !function evaluate_hb.hb_aggregation_result_fAcc_intern
  #  higher_is_better: true
metadata:
  - version: 0.0
